// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	Username    sql.NullString
	Email       string
	Password    string
	Useragent   sql.NullString
	Picture     sql.NullString
	PhoneNumber sql.NullString
	Bio         sql.NullString
	Role        sql.NullString
	GoogleID    sql.NullString
	LoginOption sql.NullString
	Revoked     sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
